### ISSUE TITLE
安装完闪退

### ISSUE THREAD

**Issue by cnryb** [donghaowxr/Android_Fast_Takephoto#1]
下面是错误日志

02-24 16:11:36.703 27209-27209/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: quickcamera.donghao.com.quickcamerademo, PID: 27209
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{quickcamera.donghao.com.quickcamerademo/quickcamera.donghao.com.quickcamerademo.MainActivity}: java.lang.RuntimeException: Fail to connect to camera service
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2441)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2501)
                                                       at android.app.ActivityThread.access$1000(ActivityThread.java:153)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5462)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                    Caused by: java.lang.RuntimeException: Fail to connect to camera service
                                                       at android.hardware.Camera.<init>(Camera.java:542)
                                                       at android.hardware.Camera.open(Camera.java:382)
                                                       at quickcamera.donghao.com.quickcamerademo.MainActivity.onCreate(MainActivity.java:50)
                                                       at android.app.Activity.performCreate(Activity.java:6303)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2394)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2501) 
                                                       at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5462) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by donghaowxr** [comment]
你好，如果刚打开程序就报Fail to connect to camera service的错误的话，可能是由于相机被其他应用程序占用导致的

**Comment by cnryb** [comment]
很抱歉，找之前找到原因了，没有及时过来反馈。
手机android版本是6.0.1，安装完之后如果在权限管理里手动给app赋予相机权限，就没有问题了
